### PR TITLE
Upload job for WildCollection category

### LINKED ISSUE #78: WildCollection upload job and model validations
_Acceptance Criteria:_
- [ ] As a user, I want to be able to upload all of the file types found in `sample_date_files/wild_collection` on the page `/file_uploads/new`.
- [ ] Tests should be written for each job similar to `spec/jobs/tagged_animal_assessment_job_spec.rb`
- [ ] Model Validations
- [ ] Unit tests for model validations

**Notes:**
Much of the logic for the file uploading/parsing is already written in the module concern `ImportJob`.

The heaviest lifting will be adding appropriate validations to the ```WildCollection``` model. Please refer to the [data dictionary](https://github.com/rubyforgood/abalone/wiki/Abalone-Data-Dictionary) and the notes below for coding these.

**For columns that have the `Facility`, let's make these foreign keys to the `Facility.rb` model we already have. There should only be certain facilities (see the `seeds.rb` file and users have the ability to add new ones.) 

`WildCollection.rb`
- Required: columns A-E, N
- See data dictionary for specific formats for tag, gonad score, predicted sex, initial holding facility, and final holding facility
- collection date, date of arrival, and OTC treatment completion date should be valid date with month, day, and year
- collection depth, length, weight should be float/integer
- Note from lab:
_I redacted some of the specific location info here, as the federal government is worried about disclosing where these endangered animals still exist in the wild, but I might not want that info in this database anyway, depending on how accessible it ends up being._

### PR DESCRIPTION
**Pull request by bsmith-optoro**
Resolves #078 

### Type of change

* New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by jtu0** [comment]
Hi @bsmith-optoro - any plans to keep working on this? if not, any objections to us branching off and incorporating your work into a new PR?

**Comment by bsmith-optoro** [comment]
I did plan to finish it, but I don't know how long it will take me with the limited amount of time I have to work on it. If someone wants to take over, that's fine. When I get a chance I'll check to see if I have any uncommitted work to push.

**Comment by jtu0** [comment]
Thanks @bsmith-optoro :heart:

We're trying to get this work wrapped up in the next few weeks so the lab can start using the app -- absolutely no pressure, but if you have a sense for how that matches up with your own schedule, can you let us know?  We'd love your help getting this across the finish line if that could work out!

**Comment by bsmith-optoro** [comment]
👍 I checked and I don't have any significant uncommitted work to get in before this get merged, just some empty classes for other job types.

**Pull request merged**
