### PR TITLE
Resolves issue #248: Audit models for validations

### LINKED ISSUE #248: Audit models for validations
@benreyn or @mdworken to flesh this out. Need to take a pass at both database level contraints and model level validations. 

Probably would be helpful to chat with some stakeholders for this.

### PR DESCRIPTION
**Pull request by mattwd7**
Resolves #248

### Description
This PR introduces a few additional Model validations to bring Rails Model validation logic to parity with Database validations. Along the way, Model specs were added for new and existing validations. Additionally, any specs missing from existing model methods were added to the spec files during this audit.

### Type of change
Technically a "Bug fix."
Validation audit and model spec audit

### How Has This Been Tested?
All new validations covered by rspec. Existing validations and model methods now covered by rspec

### CODE REVIEW

**Comment by mattwd7** [comment]
This PR may be a bit large and outside the scope of the issue in question. I am happy to break this up to make this easier on review on request!

**Comment by CraigJZ** [comment]
@mattwd7 My apologies for the delayed review. This looks great and the additional specs are a big help. Thanks for tackling this one.
Unfortunately, we introduced a conflict merging another PR. Sorry about that. Once that's resolved, we'll merge this in.

**Comment by mattwd7** [comment]
@CraigJZ all rebased!

**Review by CraigJZ — APPROVED** [review]
Thank you!! :tada:

**Pull request merged**
