### PR TITLE
[344] Allows deletion of users

### LINKED ISSUE #344: As an admin, I can delete a user for an organization
- [ ] The UsersController `destroy` action is added
- [ ] A button/link is added to the Users#index page created in #340
- [ ] This action should ask for confirmation before this destructive action is taken
- [ ] The current_user should not be allowed to perform this action on their own record
- [ ] A feature test is added that seeds a user record in the database, loads the Users#index page and clicks to delete the record, then asserts the record is no longer on the page
- [ ] Add specs that exercise the different outcomes for an admin and a user trying to perform this action. 

This task is dependent on #339 and #340

### PR DESCRIPTION
**Pull request by viniciusgama**
# Checklist:

- [x] I have performed a self-review of my own code,
- [x] I have commented my code, particularly in hard-to-understand areas,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works,
- [x] New and existing unit tests pass locally with my changes ("bundle exec rake"),
- [x] Title include "WIP" if work is in progress.

Resolves #344 

### Type of change

* New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by CraigJZ — COMMENTED** [review]
Thanks for making that change to the Makefile!!

A thought I have on the change to the index action is that it prevents an admin user from potentially reaching their own edit view, should they want to make a change to themselves.

An alternative approach might be a restriction in the destroy action that prevents @user.destroy if @user == current_user. What are your thoughts?

I also think we could merge this as is and spit handling an admin editing themself into a different story.

**Comment by viniciusgama** [comment]
> Thanks for making that change to the Makefile!!
> 
> A thought I have on the change to the index action is that it prevents an admin user from potentially reaching their own edit view, should they want to make a change to themselves.
> 
> An alternative approach might be a restriction in the destroy action that prevents `@user.destroy` if `@user == current_user`. What are your thoughts?
> 
> I also think we could merge this as is and split handling an admin editing themself into a different story.

Yeah, you are right, I just saw that the edit story would have to allow a user to update itself. I actually started by adding that check in the destroy action but thought it would be easier to hide the user.
I think I'll go with your suggestion. Another option would be to disable or hide the delete button when `user == current_user`

**Comment by CraigJZ** [comment]
> > Thanks for making that change to the Makefile!!
> > A thought I have on the change to the index action is that it prevents an admin user from potentially reaching their own edit view, should they want to make a change to themselves.
> > An alternative approach might be a restriction in the destroy action that prevents `@user.destroy` if `@user == current_user`. What are your thoughts?
> > I also think we could merge this as is and split handling an admin editing themself into a different story.
> 
> Yeah, you are right, I just saw that the edit story would have to allow a user to update itself. I actually started by adding that check in the destroy action but thought it would be easier to hide the user.
> I think I'll go with your suggestion. Another option would be to disable or hide the delete button when `user == current_user`

Thanks! I'd be fine with either of those options.

**Comment by viniciusgama** [comment]
> Thanks! I'd be fine with either of those options.

I went with both options, I thought they would complement each other nicely. You can see the changes in there 8a687b39959997b7c215b6fc9f41afb82909575d @CraigJZ

**Review by CraigJZ — APPROVED** [review]
Thanks!! Looks great!.

**Pull request merged**
